name: Publish to npm CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Publish package
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: yarn publish --non-interactive --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
